INSTALLED_APPS = (
    'prawokultury',
    'fnpdjango',

    #'events',
    'menu',
    'migdal',
    'contact',
    'chunks',

    'sponsors',
    'django_gravatar',
    'south',
    'django.contrib.comments',
    'django_comments_xtd',
    'pipeline',
    'haystack',
    'pagination',
    'sorl.thumbnail',
    'piwik',
    'django_cas',

    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.admin',
    'django.contrib.admindocs',
)
