INSTALLED_APPS = (
    'prawokultury',
    'fnpdjango',
    'menu',
    'events',
    'migdal',
    'questions',
    'shop',

    'gravatar',
    'south',
    'django.contrib.comments',
    'django_comments_xtd',
    'pipeline',
    'haystack',
    'pagination',
    'sorl.thumbnail',
    'piwik.django',
    'django_cas',
    'honeypot',
    'taggit',
    'taggit_autosuggest',
    'getpaid',
    'getpaid.backends.payu',
    'djcelery',
    'djkombu',


    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.admin',
    'django.contrib.admindocs',
    'django.contrib.sitemaps',
)
