# -*- coding: utf-8 -*-

# curl http://www.geonames.org/countries/ | grep '<a href="/countries/[^/]*/[^.]*.html">[^<]*</a>' -o | cut -d\> -f2 |
# cut -d\< -f1 | sort | sed 's/\(.*\)/    u"\1",/'

COUNTRIES = [
    u"Afghanistan",
    u"Åland",
    u"Albania",
    u"Algeria",
    u"American Samoa",
    u"Andorra",
    u"Angola",
    u"Anguilla",
    u"Antarctica",
    u"Antigua and Barbuda",
    u"Argentina",
    u"Armenia",
    u"Aruba",
    u"Australia",
    u"Austria",
    u"Azerbaijan",
    u"Bahamas",
    u"Bahrain",
    u"Bangladesh",
    u"Barbados",
    u"Belarus",
    u"Belgium",
    u"Belize",
    u"Benin",
    u"Bermuda",
    u"Bhutan",
    u"Bolivia",
    u"Bonaire",
    u"Bosnia and Herzegovina",
    u"Botswana",
    u"Bouvet Island",
    u"Brazil",
    u"British Indian Ocean Territory",
    u"British Virgin Islands",
    u"Brunei",
    u"Bulgaria",
    u"Burkina Faso",
    u"Burundi",
    u"Cambodia",
    u"Cameroon",
    u"Canada",
    u"Cape Verde",
    u"Cayman Islands",
    u"Central African Republic",
    u"Chad",
    u"Chile",
    u"China",
    u"Christmas Island",
    u"Cocos [Keeling] Islands",
    u"Colombia",
    u"Comoros",
    u"Cook Islands",
    u"Costa Rica",
    u"Croatia",
    u"Cuba",
    u"Curacao",
    u"Cyprus",
    u"Czech Republic",
    u"Democratic Republic of the Congo",
    u"Denmark",
    u"Djibouti",
    u"Dominica",
    u"Dominican Republic",
    u"East Timor",
    u"Ecuador",
    u"Egypt",
    u"El Salvador",
    u"Equatorial Guinea",
    u"Eritrea",
    u"Estonia",
    u"Ethiopia",
    u"Falkland Islands",
    u"Faroe Islands",
    u"Fiji",
    u"Finland",
    u"France",
    u"French Guiana",
    u"French Polynesia",
    u"French Southern Territories",
    u"Gabon",
    u"Gambia",
    u"Georgia",
    u"Germany",
    u"Ghana",
    u"Gibraltar",
    u"Greece",
    u"Greenland",
    u"Grenada",
    u"Guadeloupe",
    u"Guam",
    u"Guatemala",
    u"Guernsey",
    u"Guinea",
    u"Guinea-Bissau",
    u"Guyana",
    u"Haiti",
    u"Heard Island and McDonald Islands",
    u"Honduras",
    u"Hong Kong",
    u"Hungary",
    u"Iceland",
    u"India",
    u"Indonesia",
    u"Iran",
    u"Iraq",
    u"Ireland",
    u"Isle of Man",
    u"Israel",
    u"Italy",
    u"Ivory Coast",
    u"Jamaica",
    u"Japan",
    u"Jersey",
    u"Jordan",
    u"Kazakhstan",
    u"Kenya",
    u"Kiribati",
    u"Kosovo",
    u"Kuwait",
    u"Kyrgyzstan",
    u"Laos",
    u"Latvia",
    u"Lebanon",
    u"Lesotho",
    u"Liberia",
    u"Libya",
    u"Liechtenstein",
    u"Lithuania",
    u"Luxembourg",
    u"Macao",
    u"Macedonia",
    u"Madagascar",
    u"Malawi",
    u"Malaysia",
    u"Maldives",
    u"Mali",
    u"Malta",
    u"Marshall Islands",
    u"Martinique",
    u"Mauritania",
    u"Mauritius",
    u"Mayotte",
    u"Mexico",
    u"Micronesia",
    u"Moldova",
    u"Monaco",
    u"Mongolia",
    u"Montenegro",
    u"Montserrat",
    u"Morocco",
    u"Mozambique",
    u"Myanmar [Burma]",
    u"Namibia",
    u"Nauru",
    u"Nepal",
    u"Netherlands",
    u"Netherlands Antilles",
    u"New Caledonia",
    u"New Zealand",
    u"Nicaragua",
    u"Niger",
    u"Nigeria",
    u"Niue",
    u"Norfolk Island",
    u"Northern Mariana Islands",
    u"North Korea",
    u"Norway",
    u"Oman",
    u"Pakistan",
    u"Palau",
    u"Palestine",
    u"Panama",
    u"Papua New Guinea",
    u"Paraguay",
    u"Peru",
    u"Philippines",
    u"Pitcairn Islands",
    u"Poland",
    u"Portugal",
    u"Puerto Rico",
    u"Qatar",
    u"Republic of the Congo",
    u"Réunion",
    u"Romania",
    u"Russia",
    u"Rwanda",
    u"Saint Barthélemy",
    u"Saint Helena",
    u"Saint Kitts and Nevis",
    u"Saint Lucia",
    u"Saint Martin",
    u"Saint Pierre and Miquelon",
    u"Saint Vincent and the Grenadines",
    u"Samoa",
    u"San Marino",
    u"São Tomé and Príncipe",
    u"Saudi Arabia",
    u"Senegal",
    u"Serbia",
    u"Serbia and Montenegro",
    u"Seychelles",
    u"Sierra Leone",
    u"Singapore",
    u"Sint Maarten",
    u"Slovakia",
    u"Slovenia",
    u"Solomon Islands",
    u"Somalia",
    u"South Africa",
    u"South Georgia and the South Sandwich Islands",
    u"South Korea",
    u"South Sudan",
    u"Spain",
    u"Sri Lanka",
    u"Sudan",
    u"Suriname",
    u"Svalbard and Jan Mayen",
    u"Swaziland",
    u"Sweden",
    u"Switzerland",
    u"Syria",
    u"Taiwan",
    u"Tajikistan",
    u"Tanzania",
    u"Thailand",
    u"Togo",
    u"Tokelau",
    u"Tonga",
    u"Trinidad and Tobago",
    u"Tunisia",
    u"Turkey",
    u"Turkmenistan",
    u"Turks and Caicos Islands",
    u"Tuvalu",
    u"Uganda",
    u"Ukraine",
    u"United Arab Emirates",
    u"United Kingdom",
    u"United States",
    u"Uruguay",
    u"U.S. Minor Outlying Islands",
    u"U.S. Virgin Islands",
    u"Uzbekistan",
    u"Vanuatu",
    u"Vatican City",
    u"Venezuela",
    u"Vietnam",
    u"Wallis and Futuna",
    u"Western Sahara",
    u"Yemen",
    u"Zambia",
    u"Zimbabwe",
]

TRAVEL_GRANT_COUNTRIES = [
    # u"Czech Republic",
    # u"Germany",
    # u"Hungary",
    # u"Poland",
    # u"Slovakia",
]