# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-10-01 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chunk',
            options={'ordering': ('key',), 'verbose_name': 'chunk', 'verbose_name_plural': 'chunks'},
        ),
        migrations.AlterField(
            model_name='chunk',
            name='key',
            field=models.CharField(help_text='A unique name for this chunk of content', max_length=255, primary_key=True, serialize=False, verbose_name='key'),
        ),
    ]
